### ISSUE TITLE
File manager not working at all

### ISSUE THREAD

**Issue by Troyer05** [ShellAssistant/ShellAssistant#8] opened 2023-09-12 14:16 UTC
Hello, I want ot use the File Manager but the File manager litterly shows nothing and does not opperate any action. Do I need to enable this on my server or is this a bug?

**Comment by ShellAssistant** [comment] 2023-09-12 15:43
Thanks very much for reporting this issue. No, this shouldn't happen and it's not something that I've encountered before.

Would it be ok to share what type of Linux host you are connecting to? Does the shell work ok?

Any clues in the Log and Exec History under Connection Properties?

A screenshot may also provide some clues.

Thanks very much!

**Comment by Troyer05** [comment] 2023-09-13 06:12
Hello. No Problem, I will give you all Information you need, because this yould be a verry helpful function for me.
The Linux Machine is Debian 11, 64 Bit. The Shell works without any problems. I dont know wich Log i should give to you.
Maybe this Log will help? 
```
Authentication successful. Connection ready
X11 Authentication: None
X11 Authentication: None
```

I will give you a little screen record here to show you the problem. Thank you for your support. This tool is verry nice, I use it on all my computers in my company, and i am verry thankful you made this tool. 

The screen record:
https://github.com/ShellAssistant/ShellAssistant/assets/69208453/0c07b568-0585-4f35-9596-31eb585cb915

**Comment by ShellAssistant** [comment] 2023-09-16 01:08
Thanks very much for reporting this.

I can now reproduce the problem. It occurs due to a date parsing issue in German. This will occur if the language on the host you are connecting to is German. Other languages might also be affected.

The only short-term work-around at the moment would be to set the language on the host you are connecting to an English variant. You can edit this in /etc/default/locale, then reconnect. e.g.
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8

You can also use the Debian 11 desktop GUI to change the language if available.

This issue will be fixed in 0.9.4, and will also include more rigorous testing across different languages.

It would be at least a few weeks before 0.9.4 is released, but I am also considering an earlier release specifically for this issue if the release date seems to be too far off.

Glad to hear that you're enjoying using Shell Assistant. By reporting this issue, you have made the next release a little bit better.

Please let me know if you're still having trouble with the work-around, if you've any further questions, or if I can help you in any other way!

**Comment by Troyer05** [comment] 2023-09-25 09:17
Hi well i can't change the Server langunge because of some terms of services at soe programs. Hoever, I wanted you to keep me up to date if you release the new Version. Because I would really love to use this tool. 

Thank you and hope you're doing well :)

**Comment by ShellAssistant** [comment] 2023-09-29 21:15
Thanks for your patience. I've been trying to figure out what's the best way forward. I had been hoping to complete all of the features for the next release and include this locale fix at the same time. That would have been the most time efficient way. 

Unfortunately things haven't been moving as quickly as I hoped, and I really want to get this fix out. To do this, I may have to split into 2 releases. I would include this fix and some of the features in this release and the remainder in a subsequent release.

In that case, I would only have about 10 tasks to finish, then thorough testing. I'm hoping for next weekend, but I'll keep you posted if the date seems likely that it will slip.

**Comment by ShellAssistant** [comment] 2023-10-09 00:03
Thanks very much once again for your patience. I've been getting ready to release this for a few days, but there seem to be a pattern of testing everything, building for all platforms, then doing a final test and discovering a small issue, then repeating 
the process again. Sorry to keep you waiting. It's close but I think I would have to give it at least another day to be sure.

**Comment by ShellAssistant** [comment] 2023-10-09 23:08
I've released Shell Assistant 0.9.4 which I think should fix this issue.

It should be available immediately for download from the developer website, https://shellassistant.com.

It may take a few days pending review and approval before it becomes available in the Microsoft Store and the Apple App Store.

Hope this resolves your problem. I'd be grateful if you could let me know either way.

Thanks!

**Comment by Troyer05** [comment] 2023-10-10 08:06
Hey, thank you verry much for updating. I tried it and it works absolutely fine! I am verry happy, you resolved it so fast. It makes everything so easyer and faster. I defenitly will donate!! This is such a powerfull and nice tool. How can I get updated every time you will release a new version? This helps me a lot, thank you so much :)

This tool is better than anything else.

**Comment by ShellAssistant** [comment] 2023-10-16 21:12
Thanks very much for reporting this issue. I'm so happy that you're enjoying using Shell Assistant! No need to donate, but a rating or short review would be awesome if you have the time.

It should automatically update on each new release , although it can sometimes take up to a week due to incremental rollout. The update process will be different depending on whether it's downloaded from the developer website, App Store, Microsoft Store or the Snap Store.

It sounds like we can close this issue now. Thanks very much for filing this!

Please let me know if you've any further questions, or if I can help you in any other way!

**Closed as completed by ShellAssistant** 2023-10-16 21:12 UTC
