### ISSUE TITLE
file manager not working

### ISSUE THREAD

**Issue by wangrg** [ShellAssistant/ShellAssistant#9] opened 2024-01-02 03:50 UTC
<img width="624" alt="image" src="https://github.com/ShellAssistant/ShellAssistant/assets/1925650/253241f8-dfc3-4bc4-be15-31d6fcc5c0b2">

**Comment by ShellAssistant** [comment] 2024-01-22 20:42
Thanks very much for filing this issue. While there are not too many clues to go by, the only thing that I have seen that really resembles this is: https://github.com/ShellAssistant/ShellAssistant/issues/4

If so, you will see "too many sessions" reported in the sshd server's logs on the host you are connecting to when the issue occurs. You should also be able to retry the operation after you close some shells and things will work again. Increasing MaxSessions in e.g. /etc/ssh/sshd_config on the host you are connecting to will increase this limit and will alleviate the problem.

If it's not this issue, then it could indicate a possible disconnection or communication problem. Presumably this is intermittent and only happens occasionally? Toggling the connection might reconnect as a short term work-around. Any clues that might indicate a pattern in which this occurs, or might help to reproduce the problem would be greatly appreciated.

I've also fixed an issue with error propagation and other changes that will be available in future version, 0.9.6 which should provide more information about what might be happening and should also reduce the probability that this might occur.

**Comment by ShellAssistant** [comment] 2024-04-28 23:49
Thank you for filing this issue. I'm fairly sure that this is the same issue as: https://github.com/ShellAssistant/ShellAssistant/issues/4

Closing as duplicate of: https://github.com/ShellAssistant/ShellAssistant/issues/4

**Closed as completed by ShellAssistant** 2024-04-28 23:49 UTC
